# permissions for end users to edit indices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: index
    app.kubernetes.io/managed-by: kustomize
  name: index-editor-role
rules:
- apiGroups:
  - core.index.demo
  resources:
  - indices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.index.demo
  resources:
  - indices/status
  verbs:
  - get
  - update
