# permissions for end users to view indices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: index
    app.kubernetes.io/managed-by: kustomize
  name: index-viewer-role
rules:
- apiGroups:
  - core.index.demo
  resources:
  - indices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.index.demo
  resources:
  - indices/status
  verbs:
  - get
