---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - core.index.demo
  resources:
  - indices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.index.demo
  resources:
  - indices/finalizers
  verbs:
  - update
- apiGroups:
  - core.index.demo
  resources:
  - indices/status
  verbs:
  - get
  - patch
  - update
